<template>
  <aside class="admin__menu">
    <!-- agregar clase 'activo' para indicar la ruta actual -->
    <a
      href=""
      class="admin__menu-item activo">Hoy</a>
    <a
      href=""
      class="admin__menu-item">Resumen</a>
    <a
      href=""
      class="admin__menu-item">Historial</a>
    <a
      href=""
      class="admin__menu-item">Dashboard</a>
    <a
      href=""
      class="admin__menu-item">KPI</a>
    <a
      href=""
      class="admin__menu-item">Team</a>
    <a
      href=""
      class="admin__menu-item">PROMO</a>
    <a
      href=""
      class="admin__menu-item">Variables</a>
    <a
      href=""
      class="admin__menu-item">ADS</a>
    <a
      href=""
      class="admin__menu-item">Restaurant.</a>
    <a
      href=""
      class="admin__menu-item">Usuarios</a>
    <a
      href=""
      class="admin__menu-item">Quality</a>
    <a
      href=""
      class="admin__menu-item">Accounting</a>
    <a
      href=""
      class="admin__menu-item">View</a>
  </aside>
</template>
