export const stateGroups = {
  vigentes: ['started', 'waiting_for_external_payment', 'waiting_restaurant_confirmation',
    'preparing_order', 'waiting_pickup_client', 'waiting_pickup_deliveryman', 'delivering_order',
  'troubleshooting_deliveryman','troubleshooting_restaurant', 'troubleshooting_hand_off'],
  intermedio: ['started', 'waiting_restaurant_confirmation',
    'preparing_order', 'waiting_pickup_client', 'waiting_pickup_deliveryman', 'delivering_order'],
  recogidos: ['delivering_order'],
  entregados: ['order_completed'],
  problemas: ['troubleshooting_restaurant', 'troubleshooting_deliveryman', 'troubleshooting_hand_off'],
  all: ['started', 'waiting_for_external_payment', 'waiting_restaurant_confirmation',
    'preparing_order', 'waiting_pickup_client', 'waiting_pickup_deliveryman', 'delivering_order',
    'troubleshooting_restaurant', 'troubleshooting_deliveryman', 'troubleshooting_hand_off', 'order_completed',
    'order_canceled_by_troubleshooting_delivery_man', 'order_canceled_in_handoff', 'order_canceled_by_restaurant'],
  pending: ['started', 'waiting_for_external_payment', 'waiting_restaurant_confirmation',
    'preparing_order', 'waiting_pickup_client', 'waiting_pickup_deliveryman',
    'troubleshooting_restaurant'],
  solicitado: ['waiting_for_external_payment', 'waiting_restaurant_confirmation'],
  allNoCompleted: ['started', 'waiting_for_external_payment', 'waiting_restaurant_confirmation',
    'preparing_order', 'waiting_pickup_client', 'waiting_pickup_deliveryman', 'delivering_order',
    'troubleshooting_restaurant', 'troubleshooting_deliveryman', 'troubleshooting_hand_off']
}
